### ISSUE TITLE
Qbittorrent website doesn't work

### ISSUE THREAD

**Issue by OAAgamer** [thim0o/Google-Colab-QBittorrent#7] opened 2019-12-13 08:38 UTC
Website 1 says check your SSH.
Website 2 used to work, now it doesn't

**Comment by sam23-dot** [comment] 2020-05-29 17:42
yes mine too ././ plz help with the website.

**Comment by thim0o** [comment] 2021-01-04 16:04
Duplicate of #7

**Closed by thim0o** 2021-01-04 16:04 UTC
